### ISSUE TITLE
Can't run in my momentic

### ISSUE THREAD

**Issue by jabarier** [blackberry/Cascades-Samples#48]
When I download samples and import to my Momentics IDE , it can't pass compile and run . The error message like "Unresolved inclusion: <QtCore/QObject>" or "Unresolved inclusion: <QImage>".But My own project is fine . By the way , i have read the documentation's "Library support" chapter , it says 
"Qt Core , QtGui module libraray is built in to the blackberry 10 Native SDK", In my point of view, it means i can use them without addition configuration .So I have no idea about this error message , wish someone give me a hand , thanks very much .

Development enviroment lists
OSX 10.10.3
Momentics 2.1.2
API level 10.10.3

**Comment by jabarier** [comment]
> I am so sorry , it's my big mistake. I import github sample as "Existing code as blackberry c/c++ makefile project" , and when code imported , the .cproject file changed by Momentics.That's the reason why i can't run sample code 
> The wrong import way shows below

![2015-06-09 22 51 01](https://cloud.githubusercontent.com/assets/2663764/8060902/57dd6962-0efa-11e5-9d85-2144b63dbdde.png)

> The right way like this
![2015-06-09 22 54 42](https://cloud.githubusercontent.com/assets/2663764/8060940/96784c46-0efa-11e5-8e5d-4278c4c0e92c.png)

> Wish this could help you!

**Comment by timwindsor** [comment]
Thanks for posting what the solution was - I'm sure others will benefit from this detail.
